### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sid9000** [rohanliston/adobe-spritesheet-scripts#4] opened 2016-07-15 22:23 UTC
After Effects CC 2015. Win 10.

Upon running script I get this error.  "Unable to execute script at line 40. sheetifyDialogContents is undefined."

**Comment by thealexus** [comment] 2016-08-18 21:31
File SheetifyDialog.jsx, line 40:
replace 
`this.contents = sheetifyDialogContents;`
with
`this.contents = SheetifyDialogContents;`

**Comment by rohanliston** [comment] 2016-09-20 03:55
Closing as duplicate of https://github.com/rohanliston/adobe-spritesheet-scripts/issues/3

**Closed as completed by rohanliston** 2016-09-20 03:55 UTC
